"""
SQLAlchemy ORM models for the FAQ Chatbot.

Defines the structure of the database tables for FAQs and conversation logs.
"""
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey
from sqlalchemy.orm import relationship

from app.database import Base


def _get_utc_now() -> datetime:
    """Return the current UTC datetime."""
    return datetime.now(timezone.utc)


class FAQEntry(Base):
    """
    Represents an FAQ entry in the database.
    
    Attributes:
        id (int): Primary key.
        category (str): The category of the FAQ.
        question (str): The FAQ question.
        answer (str): The FAQ answer.
        created_at (datetime): When the FAQ was created.
        updated_at (datetime): When the FAQ was last updated.
    """
    __tablename__ = "faq_entries"

    id = Column(Integer, primary_key=True, index=True)
    category = Column(String, index=True, nullable=False)
    question = Column(String, nullable=False)
    answer = Column(String, nullable=False)
    created_at = Column(DateTime, default=_get_utc_now, nullable=False)
    updated_at = Column(DateTime, default=_get_utc_now, onupdate=_get_utc_now, nullable=False)


class ConversationLog(Base):
    """
    Logs interactions between users and the chatbot.
    
    Attributes:
        id (int): Primary key.
        session_id (str): Identifier for the user's session.
        user_message (str): The message sent by the user.
        bot_response (str): The response generated by the bot.
        matched_faq_id (int): Foreign key to the matched FAQ entry (if any).
        confidence_score (float): The similarity score of the match.
        timestamp (datetime): When the interaction occurred.
        feedback (str): User feedback ('positive' or 'negative', optional).
    """
    __tablename__ = "conversation_logs"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String, index=True, nullable=False)
    user_message = Column(String, nullable=False)
    bot_response = Column(String, nullable=False)
    matched_faq_id = Column(Integer, ForeignKey("faq_entries.id"), nullable=True)
    confidence_score = Column(Float, nullable=False)
    timestamp = Column(DateTime, default=_get_utc_now, nullable=False)
    feedback = Column(String, nullable=True)

    matched_faq = relationship("FAQEntry")
